#가장 좋아하는 노래 가사 구절을 적어보았습니다.
print("----------------------------")
print("  처음 내게 말했던 너의 꿈")
print("")
print("       그 크기 그대로")
print("")
print("세상에 억눌려 작아지지 않기로")
print("")
print("           약속해")
print("----------------------------")
print("     My Dear_",end="")
print("Red Velvet")
print()
